### PR TITLE
snap: tweak config moving files to copy under local/

### PR DESCRIPTION
**Pull request by albertodonato**
A few tweaks to the snap and the default config

- add another user and more groups, add user details
- move files to copy to the snap under `snap/local` as having them under `snap/` is going to be deprecated

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/candid/95/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/candid/96/

**Comment by albertodonato** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.theblues.io:8080/job/candid-merge

**Pull request merged**
