### PR TITLE
Add a test idp which authenticates against a list of users

### PR DESCRIPTION
**Pull request by albertodonato**
This is useful for testing services that need to authenticate with Candid and use the group information.

I'm not sure"local" is really a good name but I don't have a better one. Suggestions welcome :)

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/candid/89/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/candid/90/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/candid/91/

**Comment by albertodonato** [comment]
@rogpeppe I renamed the idp to "static" as you suggested

**Comment by albertodonato** [comment]
@mhilton thanks for the review, fixed the typo

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/candid/92/

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.theblues.io:8080/job/candid-merge

**Pull request merged**
